language: rust
dist: bionic
sudo: required
cache: cargo
script:
  - cargo build --verbose --all --all-features
  - cargo test --verbose --all --all-features
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
  fast_finish: true

addons:
  apt:
    packages:
      - build-essential
      - libfontconfig1-dev
      - libgraphite2-dev
      - libharfbuzz-dev
      - libicu-dev
      - libssl-dev
      - zlib1g-dev
